---
title: "Datos de cantones de Costa Rica"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r paquetes}

library(dplyr)
library(sf)
library(leaflet)
library(DT)
library(readr)
library(ggplot2)
library(plotly)

```

```{r lectura-datos}
cantones <- 
  st_read(dsn = "C:/Users/Fiorela/Downloads/cantones_simplificados.geojson", quiet = TRUE) %>%
  st_transform(4326)
```


Column {data-width=500}
-----------------------------------------------------------------------

### Mapa de cantones 

```{r}

leaflet() %>%
  addTiles(group = "OpenStreetMap") %>%
  addPolygons(data = cantones,
              weight = 1.0,
              group = "Cantones") %>%
  addLayersControl(baseGroups = c("OpenStreetMap"),
                   overlayGroups = c("Cantones"))

```

### Tabla de Cantones

```{r}
# Transformación de datos de cantones
cantones <-
  cantones %>%
  select(provincia, canton, area)

# Visualización de datos de cantones en formato tabular
cantones %>%
  st_drop_geometry() %>%
  datatable(options = list(
    pageLength = 5,
    language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
  ))

```


Column {data-width=500}
-----------------------------------------------------------------------

### Gráfico de Cantones

```{r}

# ggplotly - Gráfico de barras simples 
cantones_barras <-
  cantones %>%
  slice_max(area, n = 8) %>% 
  ggplot(aes(x = reorder(canton, -area), y = area)) +
  geom_bar(stat = "identity") +
  ggtitle("Cantones por área") +
  xlab("Cantón") +
  ylab("Área") 

ggplotly(cantones_barras) %>% config(locale = 'es')

```

